config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :boards do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
    get 'accept', to: "bookings#accept"
    get 'decline', to: "bookings#decline"
  end

  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, :price_per_day, :location, :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_location,
                  against: [:location],
                  using: { tsearch: { prefix: true } }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_many :reviews

  enum status: %i[pending confirmed declined]

  validate :cannot_book_own_board
  validates :date_check_in, :date_check_out, presence: true
  validate :not_past_check_in, :not_past_check_out
  validate :end_date_after_start_date


  private

  def cannot_book_own_board
    if board.user == user
      errors.add(:base, "You cannot book your own surfboard")
    end
  end

  def not_past_check_in
    if date_check_in.past?
      errors.add(:date_check_in, 'cannot be in the past')
    end
  end

  def not_past_check_out
    if date_check_out.past?
      errors.add(:date_check_out, 'cannot be in the past')

    end
  end

  def end_date_after_start_date
    if date_check_out < date_check_in
      errors.add(:date_check_out, "must be after the start date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :boards, through: :bookings
  has_many :bookings

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_boards, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @boards = Board.all

    if params[:query].present?
      sql_subquery = <<~SQL
        boards.location @@ :query
      SQL
      @boards = @boards.where(sql_subquery, query: params[:query])
    end

    @markers = @boards.geocoded.map do |board|
      {
        lat: board.latitude,
        lng: board.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { board: }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user

    if @board.save
      redirect_to board_path(@board), notice: 'Bookmark was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @board.update(board_params)
    redirect_to board_path(@board)
  end

  def destroy
    @board.destroy
    redirect_to bookings_path
  end

  private

  def set_boards
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:category, :description, :title, :price_per_day, :location, :photo)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :destroy]
  before_action :set_board, only: [:new, :create]

  def index
    @boards = Board.where(user: current_user)
    @bookings = Booking.where(user: current_user)
    @review = Review.new
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.board = @board
    @booking.user = current_user

    @booking.total_price = (@booking.date_check_out - @booking.date_check_in) * @board.price_per_day

    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
  end

  def update
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.confirmed!
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:booking_id])
    @booking.declined!
    redirect_to bookings_path
  end

  private


  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def booking_params
    params.require(:booking).permit(:date_check_in, :date_check_out)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @board = @booking.board
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to board_path(@board)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_info_window.html.erb
<h2><%= board.title %></h2>
<p><%= board.location %></p>

app/views/boards/_marker.html.erb
<%= image_tag "yellowboard.png", height: 40, width: 20, alt: "Logo", class:"" %>

app/views/boards/index.html.erb
<br>
<h1 class="text-center">Where do you wanna surf?</h1>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: boards_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Tell me where!"
        %>
      <%= submit_tag "Find it", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-center my-5">
  <div class="shadow" style="width: 90%; height: 400px"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>


<div class="container py-5">
  <div class="row">
    <% if @boards.any? %>
      <% @boards.each do |board| %>
        <div class="co-12 col-sm-6 col-md-4 mb-3">
          <%= link_to board_path(board), class:"text-decoration-none" do %>
            <div class="container-img">
              <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path board.photo.key, height: 300, crop: :fill %>')">
                <div class="overlay">
                  <div class="board-info">
                    <h3><%= board.title %>
                      <br>
                      <hr>
                    <%= board.price_per_day %>€</h3>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <h2><em>Sorry, ain't no boards available to surf there!</em></h2>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container py-5">
  <div class="row align-items-center">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form-card">
        <h2 class="mb-5" style="color:#404040;">Share your board with the world</h2>
        <%= simple_form_for @board do |f| %>
        <%= f.input :category, collection: ['Shortboard', 'Longboard', 'Funboard'] %>
        <%= f.input :title, placeholder: 'Channel Islands Neck Beard' %>
        <%= f.input :description, placeholder: 'Have good drive and be quick on your feet. The perfect board for the smaller days.' %>
        <%= f.input :price_per_day, placeholder: '25€' %>
        <%= f.input :location, placeholder: 'Costa da Caparica' %>

        <%= f.input :photo, as: :file %>
        <%= f.button :submit, 'Share your board', class:"btn-all", style:"width: 180px; font-weight: bold;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="d-flex justify-content-between">

  <div class="col-md-6" style="background-image: url('<%= cl_image_path @board.photo.key, height: 350, crop: :fill %>'); height: 400px; margin: 30px 20px; background-size: cover; background-position: center; border-radius: 20px; width: 300px;"></div>

  <div class="card shadow p-3 mb-5 bg-body" style="width: 20rem; margin: 20px; padding:15px; border-radius:20px;">
    <div class="card-body">
      <h5 class="card-title"><strong><%= @board.title %></strong></h5>
      <hr>
      <p class="card-text"><strong>Description: </strong><%= @board.description %>
      <p class="card-text"><strong>Location: </strong><%= @board.location %>
      <p class="card-text"><strong>Price per day: </strong><%= @board.price_per_day %>
      <br>
      <hr>

      <%= link_to "Book this board now", new_board_booking_path(@board), class:"btn-all  text-decoration-none" %>
    </div>
  </div>

  <div class="card shadow p-3 mb-5 bg-body" style="width: 20rem; margin: 20px; padding:15px; border-radius:20px;">
    <div class="card-body">
      <h5 class="card-title"><strong>Reviews</h5>
      <hr>
      <% @board.bookings.each do |booking| %>
        <% booking.reviews.each do |review| %>
          <%= "⭐" * review.rating %>
          <p class="card-text"><%= review.content %>
          <br>
          〰️〰️〰️〰️〰️〰️〰️〰️〰️〰️〰️
        <% end %>
      <% end %>


    </div>
  </div>

</div>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>


<%= @booking.id %>

app/views/bookings/index.html.erb
<div class="container">

  <div class="d-flex mb-3">
    <img src="https://img.freepik.com/premium-vector/man-character-avatar-icon-surfer-character-wetsuit-with-surfboard_51635-2323.jpg" class="card-trip-user avatar-bordered mb-4"/>
    <h5 style="margin-top: 9px; margin-left: 10px;color: black;"><%= current_user.first_name  %>'s profile</h5>
    </div>
    <hr>
    <h1>Bookings</h1>

    <div class="row">
      <% if @bookings.empty? %>
        <em>You haven't made a book yet!  <%= link_to "Go back and find a board!", boards_path, class:"btn-status text-decoration-none" %></em>
      <% end %>

      <% @bookings.each do |booking| %>
        <div class="card shadow p-3 mb-5 bg-body" style="width: 19rem; margin: 20px; padding:15px; border-radius:20px;">
          <%= cl_image_tag booking.board.photo.key, crop: :fill, class: "card-img-top", style: "border-radius: 20px; max-height: 250px" %>
          <div class="card-body">

          <h5><%= booking.board.title %></h5>

          <p>Date check in: <%= booking.date_check_in %></p>
          <p>Date check out: <%= booking.date_check_out %></p>
          <p>Status: <%= booking.status %></p>
          <hr>
          <p>Total price: <%= booking.total_price %>€</p>

          <%= link_to "Enjoyed the ride?", new_booking_review_path(booking), class:"btn-review btn" %>
          </div>
        </div>
      <% end %>
  </div>

  <hr>
  <div class="row">
    <% if @boards.any? %>
      <h1>My Boards</h1>

      <% @boards.each do |board| %>
        <div class="card shadow p-3 mb-5 bg-body" style="width: 19rem; margin: 20px; padding:15px; border-radius:20px;">
          <%= cl_image_tag board.photo.key, crop: :fill, class: "card-img-top", style: "border-radius: 20px; max-height: 250px" %>
            <div class="card-body">
              <h5><%= board.title %>
              <%= link_to board_path(board), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-regular fa-trash-can p-3" style="color:black"></i>
              <% end %></h5>
            </div>
          </div>
      <% end %>
    <hr>
  <% end %>
</div>

  <h1>Requests</h1>
    <div class="row">
      <% @boards.each do |board| %>
        <% board.bookings.each do |booking| %>
          <% if booking.pending? %>
            <div class="card shadow p-3 mb-5 bg-body" style="width: 19rem; margin: 20px; padding:15px; border-radius:20px;">
              <div class="card-body">
                <h5 class="card-title">Hey! Looks like someone wants your board!</h5>
                <hr>
                <p class="card-text"><%= booking.user.first_name %> wants to surf with your board: "<%= board.title %>"</p>
                <p class="card-text">From: <%= booking.date_check_in %></p>
                <p class="card-text">To: <%= booking.date_check_out %></p>
                <p class="card-text">Status: <%= booking.status %></p>
                  <%= link_to "Accept", booking_accept_path(booking), class: "btn-status text-decoration-none" %>
                    |
                  <%= link_to "Decline", booking_decline_path(booking), class: "btn-status text-decoration-none" %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/bookings/new.html.erb
<h1>When are we going to ride the wave rogether?</h1>

<%= simple_form_for [@board, @booking] do |f| %>
  <%= f.input :date_check_in, html5: :true %>
  <%= f.input :date_check_out, html5: :true %>

  <% if @booking.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= "You can not rent your own board" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.button :submit, "Let's swell!", class:"btn-all" %>
<% end %>

<% if @booking.errors[:base].include?("You cannot book your own surfboard") %>
  <div class="alert alert-danger rounded">
  <%= flash.now[:alert] = "You cannot book your own surfboard!" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WAVEBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://fonts.googleapis.com/css2?family=Calligraffitti&family=Lora:ital@0;1&family=Montserrat:wght@400;700&family=Rubik:wght@300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Calligraffitti&family=Lora:ital@0;1&family=Montserrat:wght@400;700&family=Roboto+Flex:wght@100;200;500;700&family=Rubik:wght@300;500&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>

    <div class="container" style="width:80%;">
      <%= render "shared/navbar" %>
      <div class="pages m-auto">
        <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>


  </body>
</html>

app/views/pages/home.html.erb
  <div class="d-flex">

    <div class="landing-page d-flex flex-column align-items-center">
      <%= image_tag "wb-logo.png", alt: "WaveBnB", width: 200 %>
      <br>
      <h2>Ready for the next <strong>SWELL</strong>?</h2>
      <h5>Surf anytime, anywhere.</h5>
      <%= link_to "FIND YOUR BOARD", boards_path, class:"btn btn-orange", style:"width: 310px" %>
    </div>

    <div class="wave-img"></div>

  </div>

app/views/reviews/new.html.erb
<h1>Tell us your experience with this board!🏄</h1>
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: (0..5) %>
  <%= f.button :submit, class:"btn-all" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="home-navbar navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <%= link_to image_tag("wb-logo.png", alt: "WaveBnB", width: 60), root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-bars-staggered fa-xl fa-rotate-180"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "All surfboards", boards_path, class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to "Share your board", new_board_path, class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "My profile", bookings_path, class:"dropdown-item" %>
              </li>
              <li><%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
            </ul>
          </li>
        </ul>
      </div>
       <% if user_signed_in? %>
          <p id="aloha">Aloha, <%= current_user.first_name  %>! </p>
          <i class="fa-regular fa-hand fa-shake fa-xl" style="color: #6b6b6b;"></i>
        <% end %>
    </div>
  </nav>